<?php

/**
 * Description of AdminPasswordProtector
 *
 * @author mikko
 */
class AdminPasswordProtector {

    public function authenticate() {
        // Workaround for authenticating with HTTP when running PHP as CGI (see also the .htaccess file):
        // http://www.besthostratings.com/articles/http-auth-php-cgi.html - Comment by Den on Apr 15, 2008 @ 01:47
        // and http://php.net/manual/en/features.http-auth.php - Comment by h3ndrik on 25-Oct-2011 12:32
        if (isset($_SERVER['REDIRECT_REMOTE_USER']) && preg_match('/Basic\s+(.*)$/i', $_SERVER['REDIRECT_REMOTE_USER'], $matches)) {
            list($name, $password) = explode(':', base64_decode($matches[1]));
            $_SERVER['PHP_AUTH_USER'] = strip_tags($name);
            $_SERVER['PHP_AUTH_PW'] = strip_tags($password);
        }

        $username = isset($_SERVER["PHP_AUTH_USER"]) ? $_SERVER["PHP_AUTH_USER"] : false;
        $password = isset($_SERVER["PHP_AUTH_PW"]) ? $_SERVER["PHP_AUTH_PW"] : false;

        if($username !== false && $password !== false){
            // Password is set, try to authenticate

            $authenticationOk = $this->http_authenticate($username, $password);

            if($authenticationOk){
                return true;
            } else {
                header('WWW-Authenticate: Basic realm="Ilmomasiinan yllapito"');
                return false;
            }

        } else {
            // Password is not set
            header('WWW-Authenticate: Basic realm="Ilmomasiinan yllapito"');
            return false;
        }
    }

    /**
     *
     * http://koivi.com/php-http-auth/
     *
     * Authenticate a user against a password file generated by Apache's httpasswd
     * using PHP rather than Apache itself.
     *
     * @param string $user The submitted user name
     * @param string $pass The submitted password
     * @param string $pass_file='.htpasswd' The system path to the htpasswd file
     * @param string $crypt_type='DES' The crypt type used to create the htpasswd file
     * @return bool
     */
    private function http_authenticate($user,$pass,$pass_file='.htpasswd',$crypt_type='DES'){

        // get the information from the htpasswd file
        $fileExists = file_exists($pass_file);
        $fileIsReadable = is_readable($pass_file);
        if($fileExists && $fileIsReadable){
            // the password file exists, open it
            if($fp=fopen($pass_file,'r')){
                while($line=fgets($fp)){
                    // for each line in the file remove line endings
                    $line=preg_replace('`[\r\n]$`','',$line);
                    list($fuser,$fpass)=explode(':',$line);
                    if($fuser==$user){
                        // the submitted user name matches this line
                        // in the file
                        switch($crypt_type){
                            case 'DES':
                                // the salt is the first 2
                                // characters for DES encryption
                                $salt=substr($fpass,0,2);

                                // use the salt to encode the
                                // submitted password
                                $test_pw=crypt($pass,$salt);
                                break;
                            case 'PLAIN':
                                $test_pw=$pass;
                                break;
                            case 'SHA':
                            case 'MD5':
                            default:
                                // unsupported crypt type
                                fclose($fp);
                                return FALSE;
                        }
                        if($test_pw == $fpass){
                            // authentication success.
                            fclose($fp);
                            return TRUE;
                        }else{
                            return FALSE;
                        }
                    }
                }
                fclose($fp);
            }else{
                // could not open the password file
                return FALSE;
            }
        }else{
            return FALSE;
        }
    }
}
